export enum InboxTypes {
    INIT_INBOX = "INIT_INBOX",
    NEW_ASSIGNMENT = "NEW_ASSIGNMENT",
    NEW_ANNOUNCEMENT = "NEW_ANNOUNCEMENT",
    NEW_ACTIVITY = "NEW_ACTIVITY",
    READ_NOTIFICATION = "READ_NOTIFICATION"
}